version: '3.8'

services:
  importer:
    build:
      context: .
      dockerfile: src/NextDnsBetBlocker.Worker.Importer/Dockerfile
    container_name: nextdns-importer
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: no
